name: Anna Marra
favicon: null
layout_spectrum: 0.7289449947420508
typography_spectrum: 0.9982373267412186
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.2870884744916111
  lightness: 0.3064348117914051
  saturation: 0.9578252367209643
  rhythmicContrast: 0.6637668025214225
purpose: []
